module.exports = {  
  config: {  
    name: "command_name",                // 🔹 Command Name  
    version: "1.0",                      // 🔸 Version  
    author: "xnil6x",                    // 👨‍💻 Developer  
    role: 4,                             // 🔐 Required Access Level  
    usePrefix: true,                     // ⛓️ Prefix Requirement  
    description: "Command Description",   // 📝 Functionality  
    guide: "Usage Guide",                // 📘 Command Syntax  
    category: "Utility",                 // 🧰 Function Category  
    cooldowns: 3                         // ⏳ Execution Delay (seconds)  
  }  
};	},
	{
		"key": "locale",
		"value": "en_US",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-03-03T13:20:05.174Z",
		"lastAccessed": "2026-03-03T13:20:05.174Z"
	},
	{
		"key": "pas",
		"value": "61571281296029%3AjhUhzpQuFo",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-03-03T13:20:05.174Z",
		"lastAccessed": "2026-03-03T13:20:05.174Z"
	},
	{
		"key": "wl_cbv",
		"value": "v2%3Bclient_version%3A3102%3Btimestamp%3A1772543715",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-03-03T13:20:05.174Z",
		"lastAccessed": "2026-03-03T13:20:05.174Z"
	},
	{
		"key": "fbl_st",
		"value": "101721150%3BT%3A29542395",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-03-03T13:20:05.174Z",
		"lastAccessed": "2026-03-03T13:20:05.174Z"
	},
	{
		"key": "vpd",
		"value": "v1%3B1039x545x1.9812500476837158",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-03-03T13:20:05.174Z",
		"lastAccessed": "2026-03-03T13:20:05.174Z"
	}
]
